### ISSUE TITLE
filter options for the beneficiary list

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#11]
format api api/beneficiary/filters/page/items-per-page?key_fied=value,  eg. /filters/1/1000?phone=10000002
* it return a dict {lists:[],count:44} , count is the total number of found items in db, length of list is smaller or equat to items-per-page.
* in order to sort by interval(smaller/bgger than) use termination __gte, __ste, eg. availability__gte=4

**Comment by valeraf** [comment]
Filter example
http://167.71.48.30:5000/api/beneficiary/filters/1/1000?availability_volunteer__gte=3&phone=69093494

**Comment by johnsmithm** [comment]
list filter items: name, phone, has_voluntar, status, sector, fixer
