### ISSUE TITLE
Create footer section

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/covid19md-voluntari-client#112]
Right now we don't have a footer section for all pages.

https://www.figma.com/file/x21w7ropzdx1mKnhkylYr9/Landing_Voluntar.md?node-id=345%3A7

**Comment by igodorogea** [comment]
I see 4 links in this section for which URLs need to be specified:
- code for moldova logo
- "Termeni și Condiții"
- Facebook
- Instagram

**Comment by unrevised6419** [comment]
@johnsmithm @andreivalcov

**Comment by andreivalcov** [comment]
> 
> 
> I see 4 links in this section for which URLs need to be specified:
> 
>     * code for moldova logo
> 
>     * "Termeni și Condiții"
> 
>     * Facebook
> 
>     * Instagram

Logo: https://code4.md/
Termeni si Conditii: linked to a new page in Figma. It's almost blank, it's ok to leave "lorem ipsum" as text placeholder.
Facebook: https://www.facebook.com/voluntar.md
Instagram: https://www.instagram.com/oamenii_initiativei/

Links can be accessed within the prototype as well, BUT:
In the right upper corner - click the "play" or "present" button. Now the file opens in Prototype mode where buttons are setup to be clickable. You can switch between Prototype and Editing mode on any Figma file, depending on your needs.
