### ISSUE TITLE
[Landing] Create "donate" section

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/covid19md-voluntari-client#113]
https://www.figma.com/file/x21w7ropzdx1mKnhkylYr9/Landing_Voluntar.md?node-id=54%3A11

**Comment by igodorogea** [comment]
More details are needed here:
1. What "Paypal" button does? (final design)?
2. "Donate now" widget - what it is about?

**Comment by andreivalcov** [comment]
> More details are needed here:
> 
> 1. What "Paypal" button does? (final design)?
> 2. "Donate now" widget - what it is about?

Hi, 
1. PayPal redirects to: https://paypal.me/ecaterinanemerenco
(removed all design versions except Final to reduce confusion) 
2. Donate now widget = Embed of campaign on Chuffed.org:
https://chuffed.org/project/initiativa-impreuna-impotriva-covid-19
