### ISSUE TITLE
[Email] Create email template "Volunteer confirmation"

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/covid19md-voluntari-client#120]
https://www.figma.com/file/x21w7ropzdx1mKnhkylYr9/Landing_Voluntar.md?node-id=515%3A357

For development can be used one of theese frameworks

- https://mjml.io/
- https://mjmlio.github.io/mjml-app/
- https://get.foundation/emails.html

**Comment by agressive-nicoleta** [comment]
Gonna do this

**Comment by unrevised6419** [comment]
🚀

**Comment by agressive-nicoleta** [comment]
10h
