### ISSUE TITLE
[Admin] Clone "Volunteers" page as "Beneficiaries"

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/covid19md-voluntari-client#131]
A new page needs to be created to show a list for all Beneficiaries.
Right now show same Volunteers data.

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=820%3A1266

**Comment by vitaliel** [comment]
Hi, I'm starting to work on it.
