### ISSUE TITLE
[Admin] Create the new request dialog

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#145]
When "cerere noua" buttom is clicked, display a dialog with the following fields, the dialog already exist, just adapt the fields, and the json send to the backend  swagger data is [here](http://185.181.229.182:5000/swagger/#/default/post_volunteers__volunteer_id_) 
- add also the longitude and latitude
- post URL /api/volunteers (no volunteer_id) 

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=656%3A103

**Comment by unrevised6419** [comment]
**Related**
- https://github.com/code4moldova/voluntar-web/issues/125
