### ISSUE TITLE
[Admin] New volunteer dialog functionality

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#146]
change the fields in the dialog as in the figma prototype

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=587%3A220

- validate the phone number
- validate the required  fields are not empty: first name, last name, phone, role, disponibilitatea

sent the post request to the same URL as the old version.

**Comment by ielixirz** [comment]
Can I work on this? thanks

and could I ask for username(email)/password for test environment thanks in advance.

**Comment by johnsmithm** [comment]
yes. username: ureche@example.com password: 123456

**Comment by ielixirz** [comment]
@johnsmithm 
basically you want this current ui

![image](https://user-images.githubusercontent.com/35192747/96695443-dc3d2300-13b3-11eb-89bb-00162cb62fb5.png)

change to this in figma right?

![image](https://user-images.githubusercontent.com/35192747/96695316-b6b01980-13b3-11eb-8f63-f7cc9e283d89.png)

**Comment by johnsmithm** [comment]
this one https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=587%3A220
![image](https://user-images.githubusercontent.com/10476109/96697120-362df080-1394-11eb-91f4-1c1f3745575f.png)

**Comment by unrevised6419** [comment]
@BaxLi working on this
