### ISSUE TITLE
Show demands on map, filter requests

### ISSUE THREAD

**Issue by unrevised6419** [code4moldova/covid19md-voluntari-client#149]
do after https://github.com/code4moldova/voluntar-backend/issues/132

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=613%3A1023

must contain:
- show the request on the map
- filter the request based on type and sector using /api/request/filters/1/5/?type=sss&zone=sss&status=confirmed

for sector filter wait this task to be done https://github.com/code4moldova/voluntar-backend/issues/131

**Comment by BaxLi** [comment]
Lucrez sa solutionez issue respectiv ..PR urmeaza

**Comment by unrevised6419** [comment]
Closed in #196
