### ISSUE TITLE
Edit and change demand status functionality

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#158]
do after #145 

when the request is "nepreluat" tab when click on "editeaza", a dialog popup appear as [here](https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=897%3A28106) . 
when click on "confirms" buttons change the status and update the list. make a PUT request to the /api/requests with the body:

```
{
     
      "_id": "5f92d96f347b42d0973eef96", 
    
      "status":"new"
    }
```

for editing of other fields use the same request body and url
here is the [figma](https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=903%3A0) design for the editing dialog

**Comment by unrevised6419** [comment]
Closed in #201
