### ISSUE TITLE
[Beneficiary] Find the coordinate for the address using the map

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#159]
When click on map icon or the address textbox, show the map, with the possibility to add the address. When clicked on the blue button from the bottom left of the popup, add the address to the textbox, and use the latitude and longitude in the json sent to the backend.

the https://dev.voluntar.md/admin/volunteers/list page already has the map functionality. use it if possible.

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=820%3A1735

![image](https://user-images.githubusercontent.com/10476109/97751863-b6bec080-1afb-11eb-926e-16bff725ca6c.png)

![image](https://user-images.githubusercontent.com/10476109/97762381-0065d600-1b11-11eb-8184-e3765612c215.png)

**Comment by johnsmithm** [comment]
also use the tomtom for autocomplete https://developer.tomtom.com/search-api/search-api-documentation

**Comment by valeraf** [comment]
assign it to me
