### ISSUE TITLE
[Volunteer] view and edit 

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#160]
must contain 
- [view volunteer details](https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=617%3A275)
- volunteer requests
- [edit volunteer](https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=617%3A1645)

**Comment by unrevised6419** [comment]
Closed with #199 and #200
