### ISSUE TITLE
Add Russian translations for the system

### ISSUE THREAD

**Issue by andreivalcov** [code4moldova/covid19md-voluntari-client#182]
**Describe the bug**
When changing language to Russian, parts of the website are still in Romanian.

**To Reproduce**

1. Go to 'voluntar.md'
2. Click on 'Русский'
3. Where exactly: (full screenshot below)

![img3](https://user-images.githubusercontent.com/72382254/104202612-ce87be80-5433-11eb-9796-7ece340189ad.png)

**Comment by unrevised6419** [comment]
In this folder we keep all localisation files https://github.com/code4moldova/voluntar-web/tree/dev/src/assets/i18n

Each language has a JSON file. We work by default with `ro.json`, everything that is added, is added here first.
And from time to time, we will try to keep updated other languages with existing keys that needs to be translated.
Maybe in the future we will automate languages sync.

For translating Russian for example, open file https://github.com/code4moldova/voluntar-web/blob/dev/src/assets/i18n/ru.json
You have to only change the values from Romanian to Russian. Do not change the keys that are in English e.g. `first_name`

You can make changes directly in GitHub. Or you can download it locally, open in an editor, translate, then write a comment here with all the content of the file, and we will update it.
