### ISSUE TITLE
[Landing] Add "Partners" section

### ISSUE THREAD

**Issue by andreivalcov** [code4moldova/covid19md-voluntari-client#183]
To be placed below "Donate" section.

![img](https://user-images.githubusercontent.com/72382254/104201156-1dccef80-5432-11eb-9b39-8155b72d5c56.png)

[Figma Prototype](https://www.figma.com/proto/x21w7ropzdx1mKnhkylYr9/Landing_Voluntar.md?node-id=515%3A1128&viewport=-1434%2C-368%2C0.4370291531085968&scaling=scale-down-width)

4 logos per row.
11 logos total, can fit in 3 slides
[Folder with logos](https://drive.google.com/drive/folders/1eRXHJN2gBX-md4z4OZJHuvCwXEYlwFTa?usp=sharing)

![img2](https://user-images.githubusercontent.com/72382254/104201444-71d7d400-5432-11eb-9998-87cbff38a92d.png)

**Comment by agressive-nicoleta** [comment]
20h (certificat)
