### ISSUE TITLE
integrate gis

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#2]
- when the streed is written a request is sent to the gis service and a list of options is returned
- user should choise the right option
- path to the [service](https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer/findAddressCandidates?City=&State=&SingleLine=mesager&category=&outFields=&maxLocations=&outSR=&searchExtent=&location=&distance=&magicKey=&f=pjson) 
- path to ui of the service [here](https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer)

**Comment by JohnnyTMD** [comment]
```
Access to XMLHttpRequest at 'https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer/findAddressCandidates?City=Chisinau&SingleLine=Vasile%20Lupu%2061/5&maxLocations=5&f=pjson' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
````
@johnsmithm  is this an public api? Seems we I have some CORS issues from localhost while testing

**Comment by johnsmithm** [comment]
@valeraf eu am incercat pe localhost in ajax si merge, si baietii de la gis au pus la cors *

 ```
$.get('https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer/findAddressCandidates?City=Chisinau&SingleLine=Vasile%20Lupu%2061/5&maxLocations=5&f=pjson',
         function(data, status){
         console.log(data);
      });

```

**Comment by grigore-fiodorov** [comment]
> ```
> Access to XMLHttpRequest at 'https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer/findAddressCandidates?City=Chisinau&SingleLine=Vasile%20Lupu%2061/5&maxLocations=5&f=pjson' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
> ```
> 
> @johnsmithm is this an public api? Seems we I have some CORS issues from localhost while testing

may be [this](https://github.com/Esri/arcgis-js-api) lib would will help you

**Comment by JohnnyTMD** [comment]
guys am găsit problema, un interceptor adăuga ceva header-uri la orice request.
