### ISSUE TITLE
[demand] add information about cluster and volunteer for in_progress, canceled and resolved demands

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#234]
- add link to the cluster to the tabs or in the edit forms
- add volunteer information like name and phone number to the edit form or the tabs

**Comment by johnsmithm** [comment]
![image](https://user-images.githubusercontent.com/10476109/110292286-a365b980-7ff5-11eb-9ef4-d68c77582cd1.png)

**Comment by unrevised6419** [comment]
Phone number is missing from backend response in `GET http://localhost:4200/api/requests/filters` in `list[].volunteer`
