### ISSUE TITLE
Replace volunteer's email with phone nr

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#28]
Replace volunteer's email with phone nr

- [x] Replace the  email column with ”Nr de tel”

- [x] Fix the bug column ”Activ”:
No matter which state of the "Active"  widget is chosen while adding/updating a volunteer, in the list of volunteers the value of the parameter "Active" is **always** "Nu"

![image](https://user-images.githubusercontent.com/62308267/78653964-89df5d80-78cc-11ea-9795-6044b431feb8.png)

**Comment by valeraf** [comment]
Done
