### ISSUE TITLE
Alert when a volunteer/beneficiary is updated/added

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#29]
Create a modal with notification which appears after clicking on the "Save"  button when a volunteer/beneficiary is updated/added. The only component of the modal is text - "Schimbările sunt salvate!/Ați creat un obiect nou cu succes!" After update/creating  -> the user is returned to the page with the updated list.

**Comment by Junumboxo** [comment]
closed until we get some details from the volunteers

**Comment by Junumboxo** [comment]
reopening

**Comment by grigore-fiodorov** [comment]
#31
