### ISSUE TITLE
hide telegram chat id if volunteer haven't and show only msg about have or not(i.e have connection to tg or not)

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4moldova/covid19md-voluntari-client#32]

**Comment by wanoo21** [comment]
Do you mean here?

![Screen Shot 2020-04-07 at 20 25 09](https://user-images.githubusercontent.com/6537167/78705623-0b0b1480-790e-11ea-9be8-08bc30851715.png)

**Comment by mihaelataranu7** [comment]
version 2.0
