### ISSUE TITLE
Change the beneficiary form

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#35]
- [x] change ”operator” in ”fixer”

- [x] secret code to be generated automatically (1 alphabet letter + 3 numbers: 1 - 10, ex. A012, A013)

- [ ] change „is curator„ in ”has curator”

![image](https://user-images.githubusercontent.com/62308267/78794418-64ca1800-79bc-11ea-805b-2705df1cfed6.png)

**Comment by valeraf** [comment]
@mihaelataranu7 
`secret code to be generated automatically`
Какой-то особенный алгоритм должен быть здесь ?
- Цифро-буквенный 
- или просто случайные цифры
- или просто буквы
- или какое-то слово со смыслом генерировать

**Comment by mihaelataranu7** [comment]
- it's needed a word with meaning (the volunteer will tell the beneficiary)

**Comment by valeraf** [comment]
Оке, это сложнее :)
Посмотрим что можно сделать

**Comment by mihaelataranu7** [comment]
http://167.71.48.30:5500/api/secret  - there 1000 possibilities
