### ISSUE TITLE
Change the form ”Create Volunteer ”

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#37]
- [x] ”Raion to change in sector + offer the following options :  Botanica, Buiucani, Centru, Ciocana, Rîșcani, suburbia
a.	Add an additional input for suburbie to insert a name
- [x] Remove the section „password„
- [x] For hours per day, give number options: 1/2/3/4/5/6/7/8
- [x] Remove all required fields except: nume, adresă, nr de tel, email
- [x] Remove section activity types
- [x] Remove last question:  ”Agreeed terms”
- [x] Change „Received Contract” in ”Contract Signed?”
![image](https://user-images.githubusercontent.com/62308267/78796471-081c2c80-79bf-11ea-8e2a-22c366551a76.png)
![image](https://user-images.githubusercontent.com/62308267/78796522-1cf8c000-79bf-11ea-99cb-3da06b46a5eb.png)
![image](https://user-images.githubusercontent.com/62308267/78796536-21bd7400-79bf-11ea-8177-a8bce331e8db.png)

**Comment by tudormd** [comment]
For hours per day, give number options: 1/2/3/4/5/6/7/8 
Backend response -
{
  "list": [
    {
      "_id": "5e8dded9027bd8429c0464fb", 
      "en": "-", 
      "is_active": true, 
      "ro": "3-4 ore pe zi", 
      "ru": "3-4 \u0447\u0430\u0441\u0430 \u0432 \u0434\u0435\u043d\u044c", 
      "select": "availability"
    }, 
    {
      "_id": "5e8ddeda027bd8429c046505", 
      "en": "-", 
      "is_active": true, 
      "ro": "1-2 ore pe zi", 
      "ru": "1-2 \u0447\u0430\u0441\u0430 \u0432 \u0434\u0435\u043d\u044c", 
      "select": "availability"
    }, 
    {
      "_id": "5e8ddedb027bd8429c046509", 
      "en": "-", 
      "is_active": true, 
      "ro": "2-3 ore pe s\u0103pt\u0103m\u00e2n\u0103", 
      "ru": "2-3 \u0447\u0430\u0441\u0430 \u0432 \u043d\u0435\u0434\u0435\u043b\u044e", 
      "select": "availability"
    }
  ]
}

**Comment by tudormd** [comment]
http://167.71.48.30:5000/api/tag/sector 
Incerc sa volosesc acest Api  - dar ca raspuns primesc  - Unauthorized Access

**Comment by mihaelataranu7** [comment]
@johnsmithm de ce nu poate utiliza API?

**Comment by tudormd** [comment]
5000 e portul pentru prod (am nevoie ca pe 5000 sa am aceleasi date)

**Comment by mihaelataranu7** [comment]
am modificat  http://167.71.48.30:5000/api/tagedit?name=availability
ar trebui să meargă acum :)
