### ISSUE TITLE
Volunteer Filters 

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#38]
- [x] Exclude all options from ”offer„, Volunteers Filters except (apeluri, transport, dezinfectare, livrare, fixing, coordonare) 
- [x] Change ”Zone Adress” in ”Sector”
- [x] Include the following options:  Botanica, Buiucani, Centru, Ciocana, Rîșcani, suburbie
- [x] Add an additional input for suburbie to insert a name
- [x] Exclude ”new volunteer” from volunteer filters

**Comment by mihaelataranu7** [comment]
![image](https://user-images.githubusercontent.com/62308267/78796988-c5a71f80-79bf-11ea-932c-5d567332f6dd.png)

**Comment by valeraf** [comment]
1 и 3 задачи 
Данные приходят из бэкенда
Надо определиться либо бэкенд нам диктует данные для списка либо мы на фронте хардкодим значения для этих списков

@mihaelataranu7 
@JohnnyTMD

**Comment by johnsmithm** [comment]
@tudormd a adaugat din frontend valori la campul 'offer' si sector in 'create form', trebuie de vazut cum a facut pentru a fi la fel si la filtre

**Comment by johnsmithm** [comment]
metoda rapida de editare a optiunilor(tags):
- asa poti vedea toate optiunile pentru sector: http://167.71.48.30:5000/api/tag/sector
- alege _id la itemul care doresti sa il stergi 
- http://167.71.48.30:5000/api/tagedit?_id=5e8e128196a3ab0290c96607&is_active=false _id=<aici pui id>
- boom, acea optiune nu mai apare in http://167.71.48.30:5000/api/tag/sector
