### ISSUE TITLE
add map

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#4]
- if the streed is not correct the user can open a map and choice the write location
- path to the [map](https://esri.github.io/esri-leaflet/examples/vector-basemap.html)
- path to th gis service [here](https://info.iharta.md:6443/arcgis/rest/services/locator/CompositeLoc/GeocodeServer)

**Comment by valeraf** [comment]
https://developers.arcgis.com/javascript/latest/guide/angular/
