### ISSUE TITLE
Typo in string on landing page

### ISSUE THREAD

**Issue by ralienpp** [code4moldova/covid19md-voluntari-client#72]
The text is right in the code: https://github.com/code4moldova/covid19md-voluntari-client/blob/b5ab0d6e05cce0335e1188e497299afd5fed4265/src/assets/i18n/ro.json#L4

But is wrong on the page:
![image](https://user-images.githubusercontent.com/295338/79117795-5ef17f80-7d8c-11ea-8cbd-e5c302a512e7.png)

**Comment by grigore-fiodorov** [comment]
need to deploy @wanoo21

**Comment by wanoo21** [comment]
@grigore-fiodorov there seems to be an error, it redirects from / to /login
Check it out on https://test.voluntar.md

**Comment by valeraf** [comment]
FIXED
