### ISSUE TITLE
Add tour for all roles

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4moldova/covid19md-voluntari-client#80]
![Screenshot_20200420_104926](https://user-images.githubusercontent.com/16736593/79727157-9912d200-82f4-11ea-8754-6dc51edf8f6b.jpg)

**Comment by mihaelataranu7** [comment]
Un moment important! După ce terminăm cu funcționalitatea, putem să ne gândim la un tour pu fiecare rol.
