### ISSUE TITLE
Add check boxes in the beneficiary form 

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#83]
In the beneficiary form, add checkboxes with the options ``yes`` or ``no``:

1. Paying by card? 2. Warm lunch? 3. Grocery? 4. Medicine? 5. Blacklist? (these options in the end of the form)

- [x] insert an icon ”black square” for beneficiaries in blacklist when display in the list, before the name

Example of checkboxes
![image](https://user-images.githubusercontent.com/62308267/79898259-a5418100-8413-11ea-97cc-f33ac535c519.png)

**Comment by johnsmithm** [comment]
in the db there is a field list: additional_info
create a machine_name for the Paying by card? 2. Warm lunch? 3. Grocery? 4. Medicine?  and if the machine name there is in the list then set to true.

**Comment by valeraf** [comment]
Done
