### ISSUE TITLE
Add 2 Boolean options in the beneficiary form

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#84]
- [x] Add Boolean data in the upper right part of beneficiary form 1.”Has disabilities?” , 2. ”Urgent?” 

- [x] if "urgent" is  true, in the beneficiary list display the beneficiary row in red colour 

- [x] if ”has disabilities?” is true, display a wheelchair icon in the beneficiary list, before the name
- [x] add an icon of " a crossed coin" before the name of a beneficiary, if "has money" is  false
![image](https://user-images.githubusercontent.com/62308267/79899209-29e0cf00-8415-11ea-8e32-f4b199537aa5.png)

**Comment by johnsmithm** [comment]
fields name in the db:
- has_disabilities
- urgent

**Comment by valeraf** [comment]
Done

**Comment by mihaelataranu7** [comment]
@valeraf I cannot see a wheelchair icon for those who have disabilities :)
