### ISSUE TITLE
Add icon "black box" for voluntaries in blacklist

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/covid19md-voluntari-client#85]
In the voluntaries' list display an icon of "black box" before the name of the voluntary for those checked in the blacklist.
![image](https://user-images.githubusercontent.com/62308267/79900569-16cefe80-8417-11ea-9b1b-39e9c7991c47.png)

**Comment by johnsmithm** [comment]
field name in the db: black_list

**Comment by valeraf** [comment]
https://prnt.sc/s4kovw
pushed
