### ISSUE TITLE
views based on role

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/covid19md-voluntari-client#9]
each user has a role[fixer, operator]
- for operator show just the new beneficiary and the list of benefiacy, no edit??
- fixer can do everything

**Comment by mihaelataranu7** [comment]
- Operator can edit the beneficiary

**Comment by mihaelataranu7** [comment]
Please, make the changes accordingly and add one more user (admin):
1. admin - has full access (volunteers, beneficiaries, users)
2. operator - access only to the beneficiary
3. fixer - access to beneficiary and volunteers

**Comment by valeraf** [comment]
Should be deployed
